# Generated by Django 4.2.29 on 2026-04-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_cards', '0003_alter_reportcard_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='intervention_type',
            field=models.CharField(choices=[('general', 'General'), ('market_demand', 'Reduce Market Demand for Wildlife'), ('poaching', 'Reduce Poaching of Wildlife'), ('trafficking', 'Reduce Trafficking of Wildlife'), ('regenerative_agriculture', 'Regenerative Agriculture'), ('habitat_protection', 'Habitat Protection')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='problem_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='results',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='tags',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
