# Generated by Django 4.2.29 on 2026-04-03 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chain', '0001_initial'),
        ('report_cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaintx',
            name='report_card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chain_tx', to='report_cards.reportcard'),
        ),
    ]
